# Insert

In [1]:
import numpy as np

In [4]:
var=np.array([1,2,3,4])
print(var)
print(type(var))

v=np.insert(var, 2, 200)
print(v)
print(var)

[1 2 3 4]
<class 'numpy.ndarray'>
[  1   2 200   3   4]
[1 2 3 4]


In [6]:
var=np.array([1,2,3,4,5,6,7,8])
print(var)
print(type(var))

v=np.insert(var, (2,4,6), 200)
print(v)

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
[  1   2 200   3   4 200   5   6 200   7   8]


In [7]:
var=np.array([1,2,3,4])
print(var)
print(type(var))

v=np.insert(var, 2, 6.8)
print(v)

[1 2 3 4]
<class 'numpy.ndarray'>
[1 2 6 3 4]


In [11]:
var1=np.array([[1,2,3,4,5],[1,2,3,4,5]])

v1=np.insert(var1, 2, 6.6, axis=0)
print(v1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [6 6 6 6 6]]


In [13]:
var1=np.array([[1,2,3,4,5],[1,2,3,4,5]])

v1=np.append(var1, 34)
print(v1)

[ 1  2  3  4  5  1  2  3  4  5 34]


# Delete

In [14]:
var2=np.array([2,4,6,8,10])
print(var2)
d=np.delete(var2, 2)
print(d)

[ 2  4  6  8 10]
[ 2  4  8 10]
