# Random

# Rand()

In [1]:
import numpy as np

In [7]:
var=np.random.rand(4)
print(var)

[0.72187579 0.68913357 0.36511127 0.64951368]


In [8]:
var1=np.random.rand(2,4)
print(var1)

[[0.41818173 0.53891658 0.15175313 0.06940629]
 [0.24383762 0.87912305 0.11586166 0.39950603]]


In [9]:
var2=np.random.rand(2,4,3)
print(var2)

[[[0.46052672 0.79660794 0.85322044]
  [0.1826272  0.27678317 0.77872229]
  [0.10080848 0.53297666 0.11023908]
  [0.16441324 0.73723719 0.03797914]]

 [[0.60510915 0.04762585 0.43642529]
  [0.03838998 0.9807082  0.54769612]
  [0.81803983 0.29827626 0.85511011]
  [0.95215448 0.0179226  0.66840058]]]


# randn()

In [10]:
var3=np.random.randn(5)
print(var3)

[-0.93363255 -1.15376405 -1.31217712 -0.22224721  0.82950451]


In [11]:
var4=np.random.randn(2,4)
print(var4)

[[-1.06489567  1.29638625 -0.11802535  1.00196433]
 [ 1.00564346  2.71992803  1.98141102 -1.4573997 ]]


# randf()

In [12]:
var5=np.random.ranf(4)
print(var5)

[0.26435034 0.84895913 0.50470892 0.60065544]


In [14]:
var6=np.random.randint(2,10)
print(var6)

9


In [15]:
var6=np.random.randint(2,10,8)
print(var6)

[9 9 9 2 6 8 9 4]
