# Shape and Reshape

In [1]:
import numpy as np

In [4]:
var=np.array([[1,2],[3,4],[5,6]])
print(var)
print(var.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [8]:
var1=np.array([1,2,3,4], ndmin=4)
print(var1)
print(var1.ndim)
print(var.shape)

[[[[1 2 3 4]]]]
4
(3, 2)


# Reshape

In [12]:
var2=np.array([1,2,3,4,5,6])
x=var2.reshape(3,2)
print(x)
print(x.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [16]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=var3.reshape(2,3,2)
print(x)
print(x.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [17]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=var3.reshape(2,3,2)
print(x)
print(x.ndim)
print()

one=x.reshape(-1)
print(one)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
